import {
  Client,
  TeamMember,
  Document,
  Project,
  Payment,
  Message,
  CouncilApplication,
  Service,
  SubService,
} from '@/types';

export const mockClients: Client[] = [
  {
    id: 'ABC123-089',
    name: 'Zafer Khan',
    email: 'zafer.khan@ai4planning.com',
    phone: '07768262279',
    address: '42 Brick Lane',
    postcode: 'E1 6RF',
    serviceType: 'residential',
    status: 'docs_uploaded',
    joinedDate: '2025-12-15',
    paymentStatus: 'completed',
    package: 'standard',
  },
  {
    id: 'cl002',
    name: 'Sarah Johnson',
    email: 'sarah.j@business.com',
    phone: '020 7946 0959',
    address: '123 Oxford Street',
    postcode: 'W1A 1AB',
    serviceType: 'commercial',
    status: 'reviewed',
    joinedDate: '2025-11-20',
    paymentStatus: 'completed',
    package: 'premium',
  },
  {
    id: 'cl003',
    name: 'Michael Chen',
    email: 'mchen@home.co.uk',
    phone: '020 7946 0960',
    address: '789 Camden High Street',
    postcode: 'NW1 7JN',
    serviceType: 'extension',
    status: 'approved',
    joinedDate: '2025-10-05',
    paymentStatus: 'completed',
    package: 'basic',
  },
  // {
  //   id: 'cl004',
  //   name: 'Emma Davis',
  //   email: 'emma.davis@email.com',
  //   phone: '020 7946 0961',
  //   address: '456 Regent Street',
  //   postcode: 'W1B 3HH',
  //   serviceType: 'residential',
  //   status: 'registered',
  //   joinedDate: '2026-01-10',
  //   paymentStatus: 'pending',
  //   package: 'standard',
  // },
  // {
  //   id: 'cl005',
  //   name: 'Thomas Wilson',
  //   email: 'twils@business.uk',
  //   phone: '020 7946 0962',
  //   address: '321 Baker Street',
  //   postcode: 'W1U 8AB',
  //   serviceType: 'commercial',
  //   status: 'docs_uploaded',
  //   joinedDate: '2025-12-01',
  //   paymentStatus: 'completed',
  //   package: 'premium',
  // },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'tm001',
    name: 'James Mitchell',
    email: 'james.mitchell@company.co.uk',
    role: 'agent_x',
    team: 'london',
    region: 'uk',
    agentCode: 'AI4P-001',
   
    isActive: true,
    defaultPassword: true,
    assignedProjects: 5,
    joinedDate: '2024-01-15',
    createdDate: '2024-01-15',
  },
  {
    id: 'tm002',
    name: 'Rebecca Thompson',
    email: 'rebecca.t@company.co.uk',
    role: 'agent_x',
    team: 'london',
    region: 'uk',
    agentCode: 'AI4P-002',
   
    isActive: true,
    defaultPassword: true,
    assignedProjects: 4,
    joinedDate: '2023-06-20',
    createdDate: '2023-06-20',
  },
  {
    id: 'tm003',
    name: 'Rajesh Patel',
    email: 'rajesh.p@company.in',
    role: 'agent_y',
    team: 'india',
    region: 'in',
    agentCode: 'AI4P-003',
   
    isActive: true,
    defaultPassword: true,
    assignedProjects: 6,
    joinedDate: '2024-03-10',
    createdDate: '2024-03-10',
  },
  {
    id: 'tm004',
    name: 'Priya Singh',
    email: 'priya.singh@company.in',
    role: 'agent_y',
    team: 'india',
    region: 'in',
    agentCode: 'AI4P-004',
   
    isActive: true,
    defaultPassword: true,
    assignedProjects: 5,
    joinedDate: '2024-02-15',
    createdDate: '2024-02-15',
  },
  {
    id: 'tm005',
    name: 'David Brown',
    email: 'david.b@company.co.uk',
    role: 'architect',
    team: 'london',
    region: 'uk',
    agentCode: 'AI4P-005',
   
    isActive: true,
    defaultPassword: false,
    assignedProjects: 3,
    joinedDate: '2023-08-05',
    createdDate: '2023-08-05',
  },
  {
    id: 'tm006',
    name: 'Alice Grant',
    email: 'alice.grant@company.co.uk',
    role: 'admin',
    team: 'london',
    region: 'uk',
    agentCode: 'AI4P-006',
   
    isActive: false,
    defaultPassword: false,
    assignedProjects: 0,
    joinedDate: '2023-01-10',
    createdDate: '2023-01-10',
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc001',
    projectId: 'PROJ-UK-7842',
    clientId: 'ABC123-089',
    name: 'Planning Application Form',
    type: 'application_form',
    uploadedDate: '2026-01-15',
    uploadedBy: 'Zafer Khan',
    fileSize: 2048,
    url: '/documents/planning-form-001.pdf',
    status: 'approved',
    version: 1,
  },
  {
    id: 'doc002',
    projectId: 'PROJ-UK-7842',
    clientId: 'ABC123-089',
    name: 'Existing Floor Plan',
    type: 'floor_plan',
    uploadedDate: '2026-01-16',
    uploadedBy: 'Zafer Khan',
    fileSize: 3072,
    url: '/documents/floor-plan-001.pdf',
    status: 'approved',
    version: 1,
  },
  {
    id: 'doc003',
    projectId: 'PROJ-UK-7843',
    clientId: 'cl002',
    name: 'Site Plan',
    type: 'site_plan',
    uploadedDate: '2026-01-18',
    uploadedBy: 'Sarah Johnson',
    fileSize: 4096,
    url: '/documents/site-plan-002.pdf',
    status: 'pending',
    version: 1,
  },
  {
    id: 'doc004',
    projectId: 'PROJ-UK-7843',
    clientId: 'cl002',
    name: 'Architect Design v1',
    type: 'design',
    uploadedDate: '2026-01-20',
    uploadedBy: 'Rajesh Patel',
    fileSize: 5120,
    url: '/documents/design-002-v1.pdf',
    status: 'requesting_update',
    version: 1,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'PROJ-UK-7842',
    clientId: 'ABC123-089',
    clientName: 'Zafer Khan',
    title: 'Residential Extension - Brick Lane',
    description: 'Adding a rear extension to existing residential property',
    serviceType: 'extension',
    location: '42 Brick Lane, London',
    postcode: 'E1 6RF',
    status: 'architect_assigned',
    createdDate: '2025-12-20',
    updatedDate: '2026-01-20',
    agentX: 'James Mitchell',
    agentY: 'Rajesh Patel',
    architect: 'David Brown',
    
    progress: 45,
    estimatedCompletionDate: '2026-03-15',
    councilReference: 'TOWER/2026/00234',
    councilName: 'Tower Hamlets Council',
    documents: [
      mockDocuments[0],
      mockDocuments[1],
    ],
  },
  // {
  //   id: 'PROJ-UK-7843',
  //   clientId: 'cl002',
  //   clientName: 'Sarah Johnson',
  //   title: 'Commercial Office Conversion',
  //   description: 'Converting warehouse space into modern office',
  //   serviceType: 'commercial',
  //   location: '123 Oxford Street, London',
  //   postcode: 'W1A 1AB',
  //   status: 'drawings_in_progress',
  //   createdDate: '2025-11-25',
  //   updatedDate: '2026-01-22',
  //   agentX: 'Rebecca Thompson',
  //   agentY: 'Priya Singh',
  //   architect: 'David Brown',
  //   progress: 65,
  //   estimatedCompletionDate: '2026-04-10',
  //   councilReference: 'WESTM/2025/10422',
  //   councilName: 'Westminster Council',
  //   documents: [
  //     mockDocuments[2],
  //     mockDocuments[3],
  //   ],
  // },
  // {
  //   id: 'proj003',
  //   clientId: 'cl003',
  //   clientName: 'Michael Chen',
  //   title: 'Single Storey Extension - Camden',
  //   description: 'Single story rear extension for family home',
  //   serviceType: 'extension',
  //   location: '789 Camden High Street, London',
  //   postcode: 'NW1 7JN',
  //   status: 'submitted_to_council',
  //   createdDate: '2025-10-10',
  //   updatedDate: '2026-01-15',
  //   agentX: 'James Mitchell',
  //   agentY: 'Rajesh Patel',
  //   architect: 'David Brown',
  //   progress: 85,
  //   estimatedCompletionDate: '2026-02-28',
  //   councilReference: 'CLLR/2025/12345',
  //   councilName: 'Islington Council',
  //   documents: [],
  // },
 
];

export const mockPayments: Payment[] = [
  {
    id: 'pay001',
    clientId: 'ABC123-089',
    clientName: 'Zafer Khan',
    projectId: 'PROJ-UK-7842',
    amount: 299,
    currency: 'GBP',
    package: 'standard',
    status: 'completed',
    transactionId: 'txn_2025_001',
    paymentMethod: 'card',
    paymentDate: '2025-12-15',
    dueDate: '2025-12-15',
    description: 'Standard Package - Residential Extension',
  },
  {
    id: 'pay002',
    clientId: 'cl002',
    clientName: 'Sarah Johnson',
    projectId: 'PROJ-UK-7843',
    amount: 599,
    currency: 'GBP',
    package: 'premium',
    status: 'completed',
    transactionId: 'txn_2025_002',
    paymentMethod: 'bank_transfer',
    paymentDate: '2025-11-20',
    dueDate: '2025-11-20',
    description: 'Premium Package - Commercial Office Conversion',
  },
  {
    id: 'pay003',
    clientId: 'cl003',
    clientName: 'Michael Chen',
    projectId: 'proj003',
    amount: 299,
    currency: 'GBP',
    package: 'basic',
    status: 'completed',
    transactionId: 'txn_2025_003',
    paymentMethod: 'card',
    paymentDate: '2025-10-05',
    dueDate: '2025-10-05',
    description: 'Basic Package - Single Storey Extension',
  },
  {
    id: 'pay004',
    clientId: 'cl004',
    clientName: 'Emma Davis',
    projectId: 'proj004',
    amount: 399,
    currency: 'GBP',
    package: 'standard',
    status: 'pending',
    transactionId: 'txn_2026_001',
    paymentMethod: 'card',
    paymentDate: '2026-01-10',
    dueDate: '2026-01-15',
    description: 'Standard Package - Residential Renovation',
  },
  {
    id: 'pay005',
    clientId: 'cl005',
    clientName: 'Thomas Wilson',
    projectId: 'proj005',
    amount: 599,
    currency: 'GBP',
    package: 'premium',
    status: 'completed',
    transactionId: 'txn_2025_005',
    paymentMethod: 'paypal',
    paymentDate: '2025-12-01',
    dueDate: '2025-12-01',
    description: 'Premium Package - Commercial Fit-Out',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg001',
    projectId: 'PROJ-UK-7842',
    from: 'James Mitchell',
    fromId: 'tm001',
    to: 'Rajesh Patel',
    toId: 'tm003',
    isGroupMessage: false,
    subject: 'Measurements for Camden project',
    body: 'Hi Rajesh, Can you confirm the site measurements for project 001? We need them ASAP for drawing preparation.',
    timestamp: '2026-01-22T10:30:00Z',
    read: true,
    priority: 'high',
  },
  {
    id: 'msg002',
    projectId: 'PROJ-UK-7842',
    from: 'Rajesh Patel',
    fromId: 'tm003',
    to: 'James Mitchell',
    toId: 'tm001',
    isGroupMessage: false,
    subject: 'Re: Measurements for Camden project',
    body: 'Measurements are ready. Sent detailed site plan separately.',
    timestamp: '2026-01-22T14:15:00Z',
    read: true,
    priority: 'normal',
  },
  {
    id: 'msg003',
    projectId: 'PROJ-UK-7843',
    from: 'Rebecca Thompson',
    fromId: 'tm002',
    to: '',
    toId: '',
    isGroupMessage: true,
    participants: ['Priya Singh', 'David Brown'],
    subject: 'Project 002 Status Update',
    body: 'Team meeting scheduled for tomorrow 10 AM. Please review current drawings and provide feedback.',
    timestamp: '2026-01-21T16:45:00Z',
    read: false,
    priority: 'normal',
  },
];

export const mockCouncilApplications: CouncilApplication[] = [
  {
    id: 'council001',
    projectId: 'proj003',
    clientName: 'Michael Chen',
    councilRef: 'CLLR/2025/12345',
    council: 'Islington Council',
    applicationDate: '2026-01-10',
    status: 'under_review',
    applicationFee: 150,
    targetDecisionDate: '2026-03-15',
    comments: 'Application is in full review. Planning officer assignment pending.',
    conditions: [],
  },
  {
    id: 'council002',
    projectId: 'PROJ-UK-7842',
    clientName: 'Zafer Khan',
    councilRef: 'TOWER/2026/00234',
    council: 'Tower Hamlets Council',
    applicationDate: '2026-01-05',
    status: 'validated',
    applicationFee: 180,
    targetDecisionDate: '2026-04-05',
    comments: 'All documents validated. Entry into formal review process scheduled for next week.',
    conditions: [],
  },
  {
    id: 'council003',
    projectId: 'proj005',
    clientName: 'Thomas Wilson',
    councilRef: 'WESTM/2025/09876',
    council: 'Westminster Council',
    applicationDate: '2025-11-15',
    status: 'approved',
    applicationFee: 250,
    targetDecisionDate: '2026-01-15',
    decisionDate: '2026-01-12',
    decision: 'Approved',
    comments: 'Application approved with standard conditions. Notice period 7 days.',
    conditions: ['Submission of details of materials within 7 days', 'Tree survey required before work begins'],
  },
];

export const mockDashboardStats = {
  totalProjects: mockProjects.length,
  activeProjects: mockProjects.filter(p => !['approved', 'rejected'].includes(p.status)).length,
  completedProjects: mockProjects.filter(p => p.status === 'approved').length,
  pendingPayments: mockPayments.filter(p => p.status === 'pending').length,
  totalRevenue: mockPayments
    .filter(p => p.status === 'completed')
    .reduce((sum, p) => sum + p.amount, 0),
  totalClients: mockClients.length,
  submittedApplications: mockCouncilApplications.filter(c => c.status !== 'draft').length,
  approvedApplications: mockCouncilApplications.filter(c => c.status === 'approved').length,
};

export const mockServices: Service[] = [
  {
    id: 'srv001',
    name: 'Residential Planning Application',
    description: 'Full planning application service for residential properties',
    category: 'residential',
    price: 599,
    duration: '4-6 weeks',
    isActive: true,
    createdDate: '2025-01-10',
    updatedDate: '2025-01-15',
    subServices: [
      {
        id: 'subsrv001',
        serviceId: 'srv001',
        name: 'Site Survey & Measurement',
        description: 'Professional site survey and detailed measurements',
        price: 150,
        estimatedHours: 4,
        isActive: true,
        createdDate: '2025-01-10',
      },
      {
        id: 'subsrv002',
        serviceId: 'srv001',
        name: 'Architectural Drawings',
        description: 'Detailed architectural and technical drawings',
        price: 250,
        estimatedHours: 16,
        isActive: true,
        createdDate: '2025-01-10',
      },
      {
        id: 'subsrv003',
        serviceId: 'srv001',
        name: 'Planning Application Submission',
        description: 'Complete application preparation and submission',
        price: 200,
        estimatedHours: 8,
        isActive: true,
        createdDate: '2025-01-10',
      },
    ],
  },
  {
    id: 'srv002',
    name: 'Commercial Planning',
    description: 'Comprehensive planning services for commercial developments',
    category: 'commercial',
    price: 1299,
    duration: '6-8 weeks',
    isActive: true,
    createdDate: '2025-01-12',
    updatedDate: '2025-01-20',
    subServices: [
      {
        id: 'subsrv004',
        serviceId: 'srv002',
        name: 'Commercial Survey',
        description: 'Detailed commercial property assessment',
        price: 300,
        estimatedHours: 8,
        isActive: true,
        createdDate: '2025-01-12',
      },
      {
        id: 'subsrv005',
        serviceId: 'srv002',
        name: 'Environmental Assessment',
        description: 'Environmental impact and sustainability analysis',
        price: 400,
        estimatedHours: 20,
        isActive: true,
        createdDate: '2025-01-12',
      },
      {
        id: 'subsrv006',
        serviceId: 'srv002',
        name: 'Council Liaison',
        description: 'Professional council communication and negotiation',
        price: 350,
        estimatedHours: 12,
        isActive: true,
        createdDate: '2025-01-12',
      },
    ],
  },
  {
    id: 'srv003',
    name: 'House Extension Service',
    description: 'Planning and design for residential extensions',
    category: 'extension',
    price: 799,
    duration: '3-4 weeks',
    isActive: true,
    createdDate: '2025-01-14',
    updatedDate: '2025-01-18',
    subServices: [
      {
        id: 'subsrv007',
        serviceId: 'srv003',
        name: 'Extension Survey',
        description: 'Structural assessment for extension feasibility',
        price: 120,
        estimatedHours: 3,
        isActive: true,
        createdDate: '2025-01-14',
      },
      {
        id: 'subsrv008',
        serviceId: 'srv003',
        name: 'Extension Drawings',
        description: 'Detailed extension design and construction drawings',
        price: 280,
        estimatedHours: 12,
        isActive: true,
        createdDate: '2025-01-14',
      },
      {
        id: 'subsrv009',
        serviceId: 'srv003',
        name: 'Building Regulations',
        description: 'Building regulations compliance and submission',
        price: 150,
        estimatedHours: 6,
        isActive: true,
        createdDate: '2025-01-14',
      },
    ],
  },
  {
    id: 'srv004',
    name: 'Planning Consultation',
    description: 'Expert advice on planning feasibility and strategy',
    category: 'consultation',
    price: 299,
    duration: '1-2 weeks',
    isActive: true,
    createdDate: '2025-01-16',
    updatedDate: '2025-01-19',
    subServices: [
      {
        id: 'subsrv010',
        serviceId: 'srv004',
        name: 'Initial Consultation',
        description: '1-hour expert planning consultation',
        price: 150,
        estimatedHours: 1,
        isActive: true,
        createdDate: '2025-01-16',
      },
      {
        id: 'subsrv011',
        serviceId: 'srv004',
        name: 'Feasibility Report',
        description: 'Detailed feasibility assessment and recommendations',
        price: 300,
        estimatedHours: 6,
        isActive: true,
        createdDate: '2025-01-16',
      },
    ],
  },
];
